### ISSUE TITLE
请问一下我运行hooks.js出现以下错误应该如何解决

### ISSUE THREAD

**Issue by leiyugithub** [WooyunDota/DroidSSLUnpinning#2]
E:\pychram\FridaProject>frida -U com.amahua.ompimdrt --no-pause -l hooks.js
     ____
    / _  |   Frida 12.2.26 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Attaching...
OkHTTP 3.x Found
com.squareup.okhttp not found
Xutils hooks not Found
httpclientandroidlib Hooks not found
TrustManagerImpl verifyChain nout found below 7.0
message: {'type': 'send', 'payload': 'Custom, Empty TrustManager ready'} data: None
[Xiaomi MI 3W::com.amahua.ompimdrt]->

我安装的是你目录下的just trust me  
小白不太懂 望解答

**Comment by WooyunDota** [comment]
这个不是justtrustme
而且这个没报错...是正常的日志..
