### ISSUE TITLE
大神，请问下JustTrustMe对多dex的apk有影响吗？

### ISSUE THREAD

**Issue by seuercc** [WooyunDota/DroidSSLUnpinning#3]
大神，请问下JustTrustMe对多dex的apk有影响吗？

**Comment by WooyunDota** [comment]
没问题的.
`        // Multi-dex support: https://github.com/rovo89/XposedBridge/issues/30#issuecomment-68486449
        findAndHookMethod("android.app.Application",
                lpparam.classLoader,
                "attach",
                Context.class,
                new XC_MethodHook() {
                    @Override
                    protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                        // Hook OkHttp or third party libraries.
                        Context context = (Context) param.args[0];
                        processOkHttp(context.getClassLoader());
                        processHttpClientAndroidLib(context.getClassLoader());
                        processXutils(context.getClassLoader());
                    }
                }
        );`
