### ISSUE TITLE
怎么使用frida来hook nativ函数的jstring返回值

### ISSUE THREAD

**Issue by zxhubo** [WooyunDota/DroidSSLUnpinning#4]
```
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO, "hooktest", __VA_ARGS__)
int getInt(int i)
{
    return i+99;
}

extern "C"   JNIEXPORT jstring   JNICALL Java_mi_ndk4frida_MainActivity_stringFromJNI(
        JNIEnv *env,
        jobject /* this */) {
    LOGI("[+] %d\n", getInt(2));
    return env->NewStringUTF("Hello from C++");
}
```
上面是示例代码，连接是这个https://xz.aliyun.com/t/2336，网上google了很多，hook native函数，都是修改返回值为int 这样的类型。那么怎么去hook NICALL Java_mi_ndk4frida_MainActivity_stringFromJNI函数修改返回值呢，其实就是修改 return env->NewStringUTF("Hello from C++"); 的值呢。

**Comment by WooyunDota** [comment]
https://github.com/WooyunDota/DroidDrops/blob/master/2018/Frida.Android.Practice.md

**Comment by zxhubo** [comment]
@WooyunDota 大佬，我的意思是修改return env->NewStringUTF("Hello from C++");这里的返回值的哦，例如改成 `Hello from Java`，在你的这个文档哪里有的呢，拜托了，困扰很久的问题

**Comment by WooyunDota** [comment]
文章末尾
var stringVar = Memory.allocUtf8String("string");
